PATCH_GENERIC_TERMS = {
    "label_text": [
        'age'.lower(),
        'all'.lower(),
        'amino acids'.lower(),
        'analysis'.lower(),
        'and'.lower(),
        'animal'.lower(),
        'animals'.lower(),
        'antibiotics'.lower(),
        'assay'.lower(),
        'bacteria'.lower(),
        'bacterial'.lower(),
        'based'.lower(),
        'body'.lower(),
        'cell death'.lower(),
        'cell'.lower(),
        'cells'.lower(),
        'cellular'.lower(),
        'chromatin'.lower(),
        'contralateral'.lower(),
        'cytoplasmic'.lower(),
        'cytosolic'.lower(),
        'dark'.lower(),
        'death'.lower(),
        'embryo'.lower(),
        'embryos'.lower(),
        'female'.lower(),
        'females'.lower(),
        'fetal'.lower(),
        'fetus'.lower(),
        'fibers'.lower(),
        'fluorescence intensity'.lower(),
        'fluorescent'.lower(),
        'gas'.lower(),
        'gland' .lower(),
        'glands'.lower(),
        'hand'.lower(),
        'IHC'.lower(),
        'individual'.lower(),
        'ipsilateral'.lower(),
        'laser'.lower(),
        'larva'.lower(),
        'larvae'.lower(),
        'light'.lower(),
        'line'.lower(),
        'littermates'.lower(),
        'lung tumor'.lower(),
        'male'.lower(),
        'males'.lower(),
        'membrane'.lower(),
        'muscles'.lower(),
        'nuclear'.lower(),
        'parasite'.lower(),
        'parasites'.lower(),
        'patient'.lower(),
        'patients'.lower(),
        'primary cell'.lower(),
        'primary cells'.lower(),
        'protein'.lower(),
        'Protein'.lower(),
        'proteins'.lower(),
        'pulse'.lower(),
        'quantification'.lower(),
        'Ratio'.lower(),
        'rest'.lower(),
        'SEM'.lower(),
        'sequence'.lower(),
        'stem'.lower(),
        'strain'.lower(),
        'tailed'.lower(),
        'TEM'.lower(),
        'temperature'.lower(),
        'test'.lower(),
        'tests'.lower(),
        'the'.lower(),
        'weeks'.lower(),
        'weight'.lower(),
        'x_cells'.lower(),
    ],
}

PATCH_GENERIC_TERMS_V2 = {
    "label_text": [
        'animal'.lower(),
        'animals'.lower(),
        'bacteria'.lower(),
        'bacterial'.lower(),
        'embryo'.lower(),
        'embryos'.lower(),
        'female'.lower(),
        'females'.lower(),
        'fetal'.lower(),
        'fetus'.lower(),
        'larva'.lower(),
        'larvae'.lower(),
        'male'.lower(),
        'males'.lower(),
        'parasite'.lower(),
        'parasites'.lower(),
        'patient'.lower(),
        'patients'.lower(),
    ],
}

UNNORMALIZED_CELLS = {'dLNs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'dPMNs': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'dPVL': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DS9': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'DU-145 DR': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'E-GFPd1 ESCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'early cortical neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EOC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EpiLC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EpiSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EpiSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EPSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EpSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'FC-1801': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'FECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'FT234': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'FT253': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'FT269': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'FXS-1': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'FXS-2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GLO': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GN11': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'GOKA': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HAFTL': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'hDASCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HDF': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HF-SCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HG cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HGSC cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hiMP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hiMPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HMLER': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'hPaca1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'hPaca2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HRMECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HRS': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hskMPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HuAR2T': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'hypoxic cell': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'Hypoxic cells': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'IPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'iPS': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'IR cells': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'ISC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ISCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'K-only': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'KB1P-B11': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KB1PM5': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KP3.33': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KPC': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KPflC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'KPM': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LAD-1': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LIF': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LKR10': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LKR13': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LRC': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'LRCs': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'LSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LTC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'M579-A2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MAIT': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MBs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MDR  cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MDR cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MEL006R': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'ML': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MNCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MODE-K': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'Mono class': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MPPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MSC2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MTO': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MyP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'necrotic': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'NKT17': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'nRH11': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'nRH12': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'nRH13': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'nRH14': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NS‐1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'orthotopic KP': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PANC-1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PaS': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pc': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PD3077': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PD454': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PD483': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PD7591': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PD798': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PD883': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PDAC8661': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PDK': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PeCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Phoenix': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'plant cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PN 04.4': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'pro-mixed': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'ps': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'putative starter cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PαS': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'R6065': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'R6141': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'R6344': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'R6430': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'residual MDR cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'RMCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'SB': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'Sb': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'SC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'SI14': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SP cells': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'Ste-1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'STE-1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'Stem Cell Memory': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TAPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TILs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TILS': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TPM': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'Tvm': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'YS-EBs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAR': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAR T cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAR T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAR T-cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAR-T cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAR-T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CARs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'multiple components': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'AdvF': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AM activated': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AM groundstate': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Bro_EC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Cap-A_EC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Cap-B_EC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CM': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CTCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'cycling cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'daughter cells': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'Tfr': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BHEL': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BPH1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'ILC2s': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DATPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AC-1': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AC-2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AC2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ACs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'AIY': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BLECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'bRG': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'colonocytes': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DATP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DATP cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DATP cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 '134-4': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 '1603MED': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 '2-cell-like': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'adipogenic progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'alveolar type II': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ANPC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ANPCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Antigen-presenting cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'APs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'APSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Areg': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Aregs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ASPC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ASPCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'autaptic neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'B intermediate': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'B lymphoid progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'B naive': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'B2 cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'basal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'basal intermediate progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Basal progenitor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'base cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'bBSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BCE': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'binucleated (BN)': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'binucleated (BN) cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'bIP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Bipolar cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'bIPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BLP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BMDMs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BN cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BOEC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BOECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'bottle shape cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'bottle-shaped cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'C4da neuron': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'c4da neuron': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'C4da neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'c4da neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAF': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CAFs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Cajal-Retzius': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Cajal-Retzius neuron': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD14 Mono': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD19+, primary B lymphocytes': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD3 lymphocyte': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD3+': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD4 M/E': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD4+ responder T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD45+ cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD45+ cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD45+ T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD4OT-II': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD8 M/E': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD8- cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD8-negative cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CD8+ T cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'central cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Central Memory': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CLESCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'club cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'club hair': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'colonic laminar propria (cLP) cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'cord blood cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'cortical cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'cortical neural progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'crown cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'crypt cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CXCR3+CCR6- memory CD4+ T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DGCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DN3 γδ-': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DN3 γδint': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DN3b γδ-': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DN3b γδ+': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DN4 γδ-': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'DN4 γδ+': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EB': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EBs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Effector Memory': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Effector Memory RA': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EM': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EMP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'EMPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'eMPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ENCC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ENCCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Endothelial Progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'enteroblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Enteroblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'enteroblasts': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'epithelial midgut cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'epithelial progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'epithelial tip progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ES cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ESC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ESP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'FAPs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'G-MDSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'gametocyte': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'gametocytes': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Gap cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'gap cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'gland base cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'globase basal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Globase basal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Glutamatergic projection neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hair germ cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HE': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HepEL': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HepELs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hMuSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hRPE': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HRPE': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hRPEs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HRPEs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HSPC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'HSPCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'iCAFs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'iHoxB4': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ILC210': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ILC3': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ILCP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'IMC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'IMCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'iMGL': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'immature neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'immune cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'imPVL': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'infiltrating immune cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Inflammatory fibroblast 1': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Inflammatory fibroblast 2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Inflammatory fibroblast 3': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Intermediate precursor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intermediate progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intermediate progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intermediate progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'interommatidial cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Intestinal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intestinal progenitor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intestinal progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intestinal progenitors cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intestinal stem cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'intestinal stem cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Intestinal Stem Cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'IPCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'islet cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'isthmus cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'kidney tubular cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'large intestinal cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lateral plate mesoderm cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Lipofibroblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'long propriospinal': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'long propriospinal neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LPSN': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'LPSNs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'luminal epithelial': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'luminal progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lung cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lymphoblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lymphoblasts': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lymphoid cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lymphoid endothelial cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'M-MDSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'M1 macrophages': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'M1-like': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'M2 macrophages': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'M2-like': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Marginal Zone Precursor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mature luminal': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mature luminal epithelial': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mature neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MB‐SCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mDA neuron': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mDA neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mDASCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MDSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MDSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Meristematic cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mesoderm cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'microglia': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mitotic cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mitotic progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MN2a': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MN3': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'multi-nucleated cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'multinuclear cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'multinucleated': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'multinucleated cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mural cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MuSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'muscle progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'muscle stem cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'muscle stem cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MuSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MyCAFs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'myCAFs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'myeloid derived suppressor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'myeloid-derived suppressor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'naïve PSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'naïve responder CD4+ T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'naïve Royan H11': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'natural killer like cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'NCC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neoblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neoblasts': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neoplastic cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Neural progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neural progenitor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neural progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neural progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neural sem cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neural-lineage cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neuroglia': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neuron': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neuronal progenitor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neuronal progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'NK Proliferating': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'non-epithelial cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'NPC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'NPCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'NSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'NSPC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Ommatidia': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ommatidia': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'OPC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'OPCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pericyte activated': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Periosteal': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Periosteal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'periosteal cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'peritoneal exudate cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'perivascular cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'perivascular cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'perivascular smooth muscle cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PGCLC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PGCLCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PGCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'photosensitive cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pigmentary cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pigmented glial cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PIME': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pit cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pit cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pluripotent cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PMN': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PMN-MDSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PMN-MDSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'post-mitotic progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Pre B cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pre-B': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pre-B cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pre-iPSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pre-OB': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'preAT1': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'primed PSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pro-differentiated': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pro-OB': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pro-pluripotent': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'progenitor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'progenitor neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'proliferating leukocyte': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'prosencephalic progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PVD': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PVD neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'PVL': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'R1 ESCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'R1 ESCs-primed': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'recirculating B cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'regrown cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'rNSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'rNSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'satellite cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'sbBSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'schistocyte': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'spindle cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'squamous cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'striatal': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'striatal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'striatal cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'striatal neurons': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'subcutaneous KP': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'synergid cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'synergid cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'systemic cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'T resident memory': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TAM': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TAM M0': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TAM M2': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TAMEMs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TAMs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TEMRA': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Terminal cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TICs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tip progenitor': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tip progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Tip progenitor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tissue resident memory T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TNG E-tdT ESCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tracheal terminal cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'transit amplifying cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Transitional lipofibroblast/myofibroblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Tregs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Tresponders': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Trm': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TRMs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Trophoblast Progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TSCM': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tubular': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tubular cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor infiltrating lymphocytes': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor-associated macrophage': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor-associated macrophages': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor-derived PC3 cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor-infiltrating immune cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor-infiltrating T cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumour infiltrating lymphocytes': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumour-associated macrophages': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'type I': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'type II alveolar epithelial cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'uncommitted lymphoid progenitors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'WAE cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'α-cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'αSMA+ cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'β-cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'β-cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'δ-cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'breast tumor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'breast tumor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'BT168FO': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'cancer cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'cancer cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Cancer stem cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CSC layers': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'CSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GB16': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GB17': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GB18': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GB4': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GBCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GBM12': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GBM43': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GBM44': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GBM5': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GS cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GSC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GSC 528': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'GSCs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'h543': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'hybridoma': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'iHCC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'leukemia  cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'leukemic cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lung adenocarcinoma cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'lung squamous carcinoma cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mammosphere': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'mammospheres': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MDR  cancer cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'melanoma cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'melanoma cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MIC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MN  cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MN cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'MN leukemic  cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'neuroblastoma cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'pancreatic tumour cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'primary leukemic T cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'prostate cancer cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Renal tumor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'SCC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TEC': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'TECs': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumor derived PC3 cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Tumors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumors': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumour cell': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'tumour cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Tumour cells': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 '3456': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '3540': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '4938': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '4953': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '10158': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '10593': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '12.64': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '24JK': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '2B4': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '3046D': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '3046M': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '3046SD': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '3046SM': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '528 GSC': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'A375-R': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'A70.2 INV-4': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'AA/C1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'AA/C1/SB': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'AlecR': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'AlectR': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'ALL-265': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BEZ hybridomas': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BJ3505': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BMK': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BT308': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BT314': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BY4741': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'C-09.10': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'C1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'C11': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'cb9': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'CRCM404': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'CRCM434': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'CRCM494': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'CTC-ITB-01': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'D20LK': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'D20LS': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'D20LSK': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'D492': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'DC3.2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'DC3.2R': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'DC3.2R cells': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '10C': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 '293T/ACE2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'A549': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'AA/C1/SB/10C': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BHP1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BMFA3': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'Bone metastatic PC3 cells': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'bone-metastatic PC3 cells': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BT12': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BT13': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'BT168': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HBEC13': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HBEC30': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HBEC34': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HCA2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HCC650': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'hovS': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'HUVECs': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'IMRB': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'Jurkat 2D10': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LCC2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LCC9': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LTi cells': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LU-NB-2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'LU-NB-3': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MB002': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MCF10CA': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'Meso-33': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM011': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM029': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM047': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM074': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM099': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM117': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM13': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MM2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MMC70': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'MP-1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'N/TERT-1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'N/TERT1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NKI8995 cell line': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NKI8996 cell line': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NKI8999 cell line': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NKI9002 cell line': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NSC24': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NSC25': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NSC5031': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'NSC8853': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PB1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PB2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PDKN1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PDKN2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'PK1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'RUES2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SBROS': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SCCO11': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SCCO13': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SCP-1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SKMEL5-R': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SN12': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SNU-4th': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'SUM159-LM1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'TG1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'TG16': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'TR1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'TR2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'vero': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'ZH305': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'merozoite': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'merozoites': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'oocyst': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'oocysts': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ookinete': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Ookinete': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'ookinetes': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'schizont': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'schizonts': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Spores': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'sporoblast': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'sporozoite': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'sporozoites': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'Sporozoites': {'entity_type': 'cell_type',
  'ext_ids': 'CL_0000000',
  'ext_dbs': 'CL',
  'ext_urls': 'https://identifiers.org/'},
 'KP': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KP.1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KP.2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KP1': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'KP2': {'entity_type': 'cell_line',
  'ext_ids': '',
  'ext_dbs': 'CVCL',
  'ext_urls': 'https://identifiers.org/cellosaurus:'},
 'apical': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'apoptotic': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'apoptotic cell': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'apoptotic cells': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'apoptotic progenitor cells': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'colonies': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''},
 'myofibers': {'entity_type': 'subcellular',
  'ext_ids': '',
  'ext_dbs': 'Gene Ontology',
  'ext_urls': 'http://amigo.geneontology.org/amigo/term/'},
 'Mabs': {'entity_type': 'subcellular',
  'ext_ids': '',
  'ext_dbs': 'Gene Ontology',
  'ext_urls': 'http://amigo.geneontology.org/amigo/term/'},
 'cilia': {'entity_type': 'subcellular',
  'ext_ids': '',
  'ext_dbs': 'Gene Ontology',
  'ext_urls': 'http://amigo.geneontology.org/amigo/term/'},
 'Polar bodies': {'entity_type': 'subcellular',
  'ext_ids': '',
  'ext_dbs': 'Gene Ontology',
  'ext_urls': 'http://amigo.geneontology.org/amigo/term/'},
 'polar body-1': {'entity_type': 'subcellular',
  'ext_ids': '',
  'ext_dbs': 'Gene Ontology',
  'ext_urls': 'http://amigo.geneontology.org/amigo/term/'},
 'cytoplast': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'cytoplasts': {'entity_type': '',
  'ext_ids': '',
  'ext_dbs': '',
  'ext_urls': ''},
 'granule cell layer': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'iRPE': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'PDX': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'PDX118': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'MYO': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'neurosphere': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'neurospheres': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'Oncosphere': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'oncospheres': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'supra-basal': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'spheres': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'spheroids': {'entity_type': 'tissue',
  'ext_ids': '',
  'ext_dbs': 'Uberon',
  'ext_urls': 'https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_'},
 'text': {'entity_type': '', 'ext_ids': '', 'ext_dbs': '', 'ext_urls': ''}
 }