PATCH_GENERIC_TERMS = {
    "label_text": [
        'age'.lower(),
        'all'.lower(),
        'amino acids'.lower(),
        'analysis'.lower(),
        'and'.lower(),
        'animal'.lower(),
        'animals'.lower(),
        'antibiotics'.lower(),
        'assay'.lower(),
        'bacteria'.lower(),
        'bacterial'.lower(),
        'based'.lower(),
        'body'.lower(),
        'cell death'.lower(),
        'cell'.lower(),
        'cells'.lower(),
        'cellular'.lower(),
        'chromatin'.lower(),
        'contralateral'.lower(),
        'cytoplasmic'.lower(),
        'cytosolic'.lower(),
        'dark'.lower(),
        'death'.lower(),
        'embryo'.lower(),
        'embryos'.lower(),
        'female'.lower(),
        'females'.lower(),
        'fetal'.lower(),
        'fetus'.lower(),
        'fibers'.lower(),
        'fluorescence intensity'.lower(),
        'fluorescent'.lower(),
        'gas'.lower(),
        'gland' .lower(),
        'glands'.lower(),
        'hand'.lower(),
        'IHC'.lower(),
        'individual'.lower(),
        'ipsilateral'.lower(),
        'laser'.lower(),
        'larva'.lower(),
        'larvae'.lower(),
        'light'.lower(),
        'line'.lower(),
        'littermates'.lower(),
        'lung tumor'.lower(),
        'male'.lower(),
        'males'.lower(),
        'membrane'.lower(),
        'muscles'.lower(),
        'nuclear'.lower(),
        'parasite'.lower(),
        'parasites'.lower(),
        'patient'.lower(),
        'patients'.lower(),
        'primary cell'.lower(),
        'primary cells'.lower(),
        'protein'.lower(),
        'Protein'.lower(),
        'proteins'.lower(),
        'pulse'.lower(),
        'quantification'.lower(),
        'Ratio'.lower(),
        'rest'.lower(),
        'SEM'.lower(),
        'sequence'.lower(),
        'stem'.lower(),
        'strain'.lower(),
        'tailed'.lower(),
        'TEM'.lower(),
        'temperature'.lower(),
        'test'.lower(),
        'tests'.lower(),
        'the'.lower(),
        'weeks'.lower(),
        'weight'.lower(),
        'x_cells'.lower(),
    ],
}

PATCH_GENERIC_TERMS_V2 = {
    "label_text": [
        'animal'.lower(),
        'animals'.lower(),
        'bacteria'.lower(),
        'bacterial'.lower(),
        'embryo'.lower(),
        'embryos'.lower(),
        'female'.lower(),
        'females'.lower(),
        'fetal'.lower(),
        'fetus'.lower(),
        'larva'.lower(),
        'larvae'.lower(),
        'male'.lower(),
        'males'.lower(),
        'parasite'.lower(),
        'parasites'.lower(),
        'patient'.lower(),
        'patients'.lower(),
    ],
}
