version: '3'

services:
  nlp:
    build:
      context: .
      dockerfile: Dockerfile
      # args: # abandoning this for now, transfomers needs to be able to mkdir /.cache
      #   - user_id=${USER_ID}
      #   - group_id=${GROUP_ID}
    image: soda_data
    volumes: &volumes
    - .:/app
    - ./data:/data
    - ./cache:${CACHE}
    # - ./dummy:${DUMMY_DIR}
    env_file:
    - ./.env
    ports:
      - 8891:8891  # this allows to run jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
    working_dir: /app
    command: ["jupyter", "notebook", "--port=8891", "--ip=0.0.0.0", "--allow-root"]

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_allow__upgrade=${NEO4J_dbms_allow__upgrade}
      - NEO4J_AUTH=${NEO_USERNAME}/${NEO_PASSWORD}
      # - EXTENSION_SCRIPT=/app/neo4j-init.sh
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - ./data/neo4j-data:/data
      - ./data/neo4j-logs:/logs
      - ./data/neo4j-plugins:/plugins
      - ./data/neo4j-import:/import
    env_file:
      - .env
    ports:
      - "7481:7474"
      - "7691:7687"
  redis:
    image: redis:6
    volumes:
      - ./data/redis-data:/data
